name: PinataPartyAddon
main: com.josemarcellio.pinatapartyaddon.PinataPartyAddon
version: 1.0.0
author: JoseMarcellio
description: "PinataParty Disguises Addon by JoseMarcellio"
depend:
  - LibsDisguises
  - PinataParty
commands:
  pinatapartyaddonreload:
    aliases:
      - ppar
      - ppareload